title: Demonic Tricycle - ELECH309
description: ELECH309 Project - Fonteyn, Placentino, Powis
theme: just-the-docs

url: https://dev.demonictricycle-dev.pages.dev

aux_links:
  Github Repository: https://github.com/DemonicTricycle/DemonicTricycle-ELECH309
